baseURL = "https://xumj2021.github.io"

title = "Mengjie Xu"
theme = "hugo-theme-cleanwhite-rsy"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "http://ww1.sinaimg.cn/large/008iTKOogy1grhxp4ei4yj32yo1o07rz.jpg"
  title = "Learning By Doing"
  SEOTitle = "Mengjie Xu's Blog"
  keyword = "Mengjie, Xu, Python, Stata, Econometrics, Accounting, Crawling"
 
  # Sidebar settings
  sidebar_about_description = "A Second-Year Phd Student at Frankfurt School of Finance and Mangement"
  sidebar_avatar = "https://img-blog.csdnimg.cn/20210614174705241.png"
  about_me = true

  #featured_tags = flase 
  #featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "https://img-blog.csdnimg.cn/20210614174700794.png"
  title_404 = "The page is missing"

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "m.xu@fs.de"
  github         = "https://github.com/xumj2021"
  Twitter        = "https://twitter.com/xumj2021"
